import Head from "next/head";
import Image from "next/image";
import { doggypic } from "@/pages/api/doggypic.js";
import { useState, useEffect } from "react";

export default function Home({ imgUrl: defaultImgUrl }) {
  const [dogData, setDogData] = useState({
    imgUrl: "https://images.dog.ceo/breeds/pekinese/n02086079_15220.jpg",
    breedName1: "A",
    breedName2: "B",
    breedName3: "C",
    breedName4: "D",
  });

  // returns the breedname from the url
  function displayBreedName(url) {
    const regex = /\/breeds\/([a-zA-Z-]+)/;
    const match = url.match(regex);
    const breedName = match[1];
    return breedName;
  }

  // turns button green if correct answer and red if incorrect
  const handleButtonClick = (breedName, event) => {
    if (breedName === displayBreedName(dogData.imgUrl)) {
      event.target.style.backgroundColor = "green";
    } else {
      event.target.style.backgroundColor = "red";
    }
  };

  //allows renders to update
  useEffect(() => {
    if (!defaultImgUrl) {
      const fetchDogPic = async () => {
        const { imgUrl } = await doggypic();
        setDogData((prevState) => ({ ...prevState, imgUrl }));
      };
      fetchDogPic();
    }
  }, []);

  //updates dog breeds and resets button background colour
  const handleClick = async () => {
    const { imgUrl, breedName1, breedName2, breedName3, breedName4 } =
      await doggypic();
    setDogData({ imgUrl, breedName1, breedName2, breedName3, breedName4 });
    const buttons = document.querySelectorAll("button");
    buttons.forEach((button) => {
      button.style.backgroundColor = "";
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <nav id="navbar">
        <h3>DogNerdle</h3>
           <div id="paw">
          <Image src="/paw-solid.svg" alt="paw" width={60} height={120} />
        </div>
      </nav>

      <div id="landingpage">
        <h1>Hello Dog Nerds!</h1>

        <div id="imagecontainer">
          <img id="dogpic" src={dogData.imgUrl} alt={""} />
        </div>
        <div id="answers">
          <button
            id="button1"
            className="button"
            onClick={(event) => handleButtonClick(dogData.breedName1, event)}
          >
            {dogData.breedName1}
          </button>
          <button
            id="button2"
            className="button"
            onClick={(event) => handleButtonClick(dogData.breedName2, event)}
          >
            {dogData.breedName2}
          </button>
          <button
            id="button3"
            className="button"
            onClick={(event) => handleButtonClick(dogData.breedName3, event)}
          >
            {dogData.breedName3}
          </button>
          <button
            id="button4"
            className="button"
            onClick={(event) => handleButtonClick(dogData.breedName4, event)}
          >
            {dogData.breedName4}
          </button>
        </div>
        <button id="button5" onClick={handleClick}>
          Play Again
        </button>
      </div>
      <footer id="footer"><h4>Terms & Conditions....Have fun!</h4></footer> 
    </>
  );
}

export async function getServerSideProps() {
  const { imgUrl, breedName1, breedName2, breedName3, breedName4 } =
    await doggypic();
  console.log(
    "Server-side data:",
    imgUrl,
    breedName1,
    breedName2,
    breedName3,
    breedName4
  );
  return {
    props: { imgUrl, breedName1, breedName2, breedName3, breedName4 },
  };
}
